---
- hosts: localhost
  connection: local

  vars:
    homebrew_install_path: /usr/local/homebrew
    homebrew_installed_packages:
      - ansible
      - git
      - dockutil
      - openconnect
      - cask

    homebrew_taps:
      - caskroom/cask
      - caskroom/versions

    homebrew_cask_appdir: /Applications
    homebrew_cask_apps:
      - firefox
      - emacs
      - spotify
      - slack
      - lastpass

    dockitems_to_remove:
      - Siri
      - Launchpad
      - Safari
      - Mail
      - Contacts
      - Maps
      - Photos
      - Messages
      - FaceTime
      - Pages
      - Numbers
      - Keynote
      - iTunes
      - iBooks

    dockitems_to_persist:
      - name: Firefox
        path: "/Applications/Firefox.app"
        pos: 1
      - name: Emacs
        path: "/Applications/Emacs.app"
        pos: 2
      - name: Terminal
        path: "/Applications/Utilities/Terminal.app"
        pos: 3
      - name: Spotify
        path: "/Applications/Spotify.app"
        pos: 4
      - name: Slack
        path: "/Applications/Slack.app"
        pos: 5

  roles:
    - geerlingguy.homebrew
    - dock
