#!/usr/bin/env bash

if [[ `fdesetup status` != "FileVault is On." ]]; then
    sudo fdesetup enable
fi

xcode-select --install
sudo easy_install pip
sudo pip install ansible

ansible-galaxy install -r requirements.yml
ansible-playbook main.yml -i inventory -K
